name: docker-tests-marklogic_python

services:

  marklogic:
    image: "${MARKLOGIC_IMAGE}"
    platform: linux/amd64
    environment:
      - INSTALL_CONVERTERS=true
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ${MARKLOGIC_LOGS_VOLUME}:/var/opt/MarkLogic/Logs
    ports:
      - "8000-8002:8000-8002"
      - "8030-8031:8030-8031"
